import type { Metadata } from 'next'
import Sidebar from './components/Sidebar'
 
// These styles apply to every route in the application
import '../global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
      <div className="flex min-h-screen">
        <aside className="w-60 bg-gray-100">
          <Sidebar />
        </aside>
        <main className="flex-1 p-4">
          {children}
        </main>
      </div>
    </body>
  </html>
  )
}